using Newtonsoft.Json;
//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace Tester.Topic.Models
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// This schema uses 'additionalProperties: false' to ensure strict validation by disallowing properties not explicitly defined in the schema.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Eopitemtrackingshippingnexusv1value
    {
        /// <summary>
        /// Message metadata
        /// </summary>
        [Newtonsoft.Json.JsonProperty("metadata", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [JsonRequired]
                public required Metadata Metadata { get; set; }

        /// <summary>
        /// Shipping manifest
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [JsonRequired]
                public required Shipping Shipping { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Metadata
    {
        /// <summary>
        /// Global id of the operation that originated this message. Used for tracking the operation on all the services involved
        /// </summary>
        [Newtonsoft.Json.JsonProperty("correlation_id", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [JsonRequired]
                public required string CorrelationId { get; set; }

        /// <summary>
        /// id of the json schema associated with this message
        /// </summary>
        [Newtonsoft.Json.JsonProperty("data_type", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [JsonRequired]
                public required string DataType { get; set; }

        /// <summary>
        /// Local id of the operation that originated this message. This id is local to the service/microservice that originated the message
        /// </summary>
        [Newtonsoft.Json.JsonProperty("interchange_id", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [JsonRequired]
                public required System.Guid InterchangeId { get; set; }

        /// <summary>
        /// id of the service/microservice that generated this message
        /// </summary>
        [Newtonsoft.Json.JsonProperty("source", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [JsonRequired]
                public required string Source { get; set; }

        /// <summary>
        /// Date when this message was generated
        /// </summary>
        [Newtonsoft.Json.JsonProperty("timestamp", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [JsonRequired]
                public required System.DateTimeOffset Timestamp { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Shipping
    {
        /// <summary>
        /// Additional services list in CTT system is equivalent to special services
        /// </summary>
        [Newtonsoft.Json.JsonProperty("additionals", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [JsonRequired]
                public required System.Collections.Generic.ICollection<Additionals> Additionals { get; set; }

        [Newtonsoft.Json.JsonProperty("audit", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [JsonRequired]
                public required Audit Audit { get; set; }

        /// <summary>
        /// Code of the client center this manifest is associated with
        /// </summary>
        [Newtonsoft.Json.JsonProperty("client_center_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        public string ClientCenterCode { get; set; }

        /// <summary>
        /// Code of the client this manifest is associated with used in CTT - Correios de Portugal systems
        /// </summary>
        [Newtonsoft.Json.JsonProperty("client_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        public string ClientCode { get; set; }

        /// <summary>
        /// Code of the client this manifest is associated with used in CTT Express systems
        /// </summary>
        [Newtonsoft.Json.JsonProperty("client_code_es", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        public string ClientCodeEs { get; set; }

        /// <summary>
        /// Shipping client hub code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("client_hub_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ClientHubCode { get; set; }

        /// <summary>
        /// Client References list
        /// </summary>
        [Newtonsoft.Json.JsonProperty("client_references", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string> ClientReferences { get; set; }

        /// <summary>
        /// Contract code used in CTT Correios de Portugal systems
        /// </summary>
        [Newtonsoft.Json.JsonProperty("contract_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        public string ContractCode { get; set; }

        /// <summary>
        /// Declared Committed Delivery datetime (ISO 8601)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("declared_committed_delivery_datetime", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? DeclaredCommittedDeliveryDatetime { get; set; }

        /// <summary>
        /// Delivery details
        /// </summary>
        [Newtonsoft.Json.JsonProperty("delivery", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Delivery Delivery { get; set; }

        /// <summary>
        /// Shipping destination address (Address where the shipment must be delivered)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destin_address", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(256)]
        [JsonRequired]
                public required string DestinAddress { get; set; }

        /// <summary>
        /// Destination country code (Country where the shipment must be delivered)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destin_country_code", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(2, MinimumLength = 2)]
        [JsonRequired]
                public required string DestinCountryCode { get; set; }

        /// <summary>
        /// Shipping destination hub code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destin_hub_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string DestinHubCode { get; set; }

        /// <summary>
        /// Name of the destination hub
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destin_hub_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string DestinHubName { get; set; }

        /// <summary>
        /// Destination Name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destin_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string DestinName { get; set; }

        /// <summary>
        /// Destination Postal Code (Postal Code where the shipment must be delivered)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destin_postal_code", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [JsonRequired]
                public required string DestinPostalCode { get; set; }

        /// <summary>
        /// Shipping destination town name (Town where the shipment must be delivered)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("destin_town_name", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        [JsonRequired]
                public required string DestinTownName { get; set; }

        /// <summary>
        /// Information for devolution process
        /// </summary>
        [Newtonsoft.Json.JsonProperty("devolution", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Devolution Devolution { get; set; }

        /// <summary>
        /// Dispash Number used by CTT - Correios de Portugal
        /// </summary>
        [Newtonsoft.Json.JsonProperty("dispatch_number", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string DispatchNumber { get; set; }

        /// <summary>
        /// Expedition code used by CTT - Correios de Portugal
        /// </summary>
        [Newtonsoft.Json.JsonProperty("expedition_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ExpeditionCode { get; set; }

        /// <summary>
        /// Indicates that the shipping is a devolution
        /// </summary>
        [Newtonsoft.Json.JsonProperty("is_devolution", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? IsDevolution { get; set; } = false;

        /// <summary>
        /// Indicates that the is a shipment (remessa)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("is_expedition_prime", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? IsExpeditionPrime { get; set; } = false;

        /// <summary>
        /// Indicates that the shipping is a return (back)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("is_return", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? IsReturn { get; set; } = false;

        /// <summary>
        /// Shipping item list
        /// </summary>
        [Newtonsoft.Json.JsonProperty("items", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        [JsonRequired]
                public required System.Collections.Generic.ICollection<Items> Items { get; set; }

        /// <summary>
        /// Total number of items for this shipping
        /// </summary>
        [Newtonsoft.Json.JsonProperty("items_count", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Range(1, 999)]
        [JsonRequired]
                public required int ItemsCount { get; set; }

        /// <summary>
        /// Datetime when the manifest were created
        /// </summary>
        [Newtonsoft.Json.JsonProperty("manifest_datetime", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [JsonRequired]
                public required System.DateTimeOffset ManifestDatetime { get; set; }

        /// <summary>
        /// Origin Address (Address where you have to go to pick up the shipment)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("origin_address", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(256)]
        [JsonRequired]
                public required string OriginAddress { get; set; }

        /// <summary>
        /// Origin country code (Country where you have to go to pick up the shipment) ISO-ALFA2
        /// </summary>
        [Newtonsoft.Json.JsonProperty("origin_country_code", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(2, MinimumLength = 2)]
        [JsonRequired]
                public required string OriginCountryCode { get; set; }

        /// <summary>
        /// Shipping origin hub code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("origin_hub_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        public string OriginHubCode { get; set; }

        /// <summary>
        /// Origin Postal Code (Postal Code where you have to go to pick up the shipment)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("origin_postal_code", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [JsonRequired]
                public required string OriginPostalCode { get; set; }

        /// <summary>
        /// The name of the origin town (Town where you have to go to pick up the shipment)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("origin_town_name", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        [JsonRequired]
                public required string OriginTownName { get; set; }

        /// <summary>
        /// Code of the provider
        /// </summary>
        [Newtonsoft.Json.JsonProperty("provider_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ProviderCode { get; set; }

        /// <summary>
        /// Shipping code assigned by the external provider
        /// </summary>
        [Newtonsoft.Json.JsonProperty("provider_shipping_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        public string ProviderShippingCode { get; set; }

        /// <summary>
        /// Recipient address
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_address", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(256)]
        public string RecipientAddress { get; set; }

        /// <summary>
        /// Recipient Country Code. ISO 3166 ALPHA-2 format
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_country_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(2, MinimumLength = 2)]
        public string RecipientCountryCode { get; set; }

        /// <summary>
        /// Recipient email address for notifications
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_email_notify_address", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string RecipientEmailNotifyAddress { get; set; }

        /// <summary>
        /// Recipient Name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_name", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        [JsonRequired]
                public required string RecipientName { get; set; }

        /// <summary>
        /// Recipient Phones list
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_phones", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string> RecipientPhones { get; set; }

        /// <summary>
        /// Recipient postal code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_postal_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        public string RecipientPostalCode { get; set; }

        /// <summary>
        /// Recipient References list
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_references", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string> RecipientReferences { get; set; }

        /// <summary>
        /// Recipient town name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("recipient_town_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string RecipientTownName { get; set; }

        /// <summary>
        /// Related Shippings
        /// </summary>
        [Newtonsoft.Json.JsonProperty("related_services", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<RelatedServices> RelatedServices { get; set; }

        /// <summary>
        /// Number of backs
        /// </summary>
        [Newtonsoft.Json.JsonProperty("return_count", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int? ReturnCount { get; set; }

        /// <summary>
        /// Sender address
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sender_address", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(256)]
        public string SenderAddress { get; set; }

        /// <summary>
        /// Sender country code. Default: Spain (ES). ISO 3166 ALPHA-2 format
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sender_country_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(2, MinimumLength = 2)]
        public string SenderCountryCode { get; set; }

        /// <summary>
        /// Sender email address for notifications
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sender_email_notify_address", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string SenderEmailNotifyAddress { get; set; }

        /// <summary>
        /// Sender name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sender_name", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        [JsonRequired]
                public required string SenderName { get; set; }

        /// <summary>
        /// Sender phone list
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sender_phones", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string> SenderPhones { get; set; }

        /// <summary>
        /// Sender postal code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sender_postal_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        public string SenderPostalCode { get; set; }

        /// <summary>
        /// Sender town name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sender_town_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string SenderTownName { get; set; }

        /// <summary>
        /// Shipping code for this manifest used by CTT - Correios de Portugal
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping_code", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [JsonRequired]
                public required string ShippingCode { get; set; }

        [Newtonsoft.Json.JsonProperty("shipping_code_es", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^\d{22}$")]
        public string ShippingCodeEs { get; set; }

        /// <summary>
        /// This field was previously known as `client_date`.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping_date", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(DateFormatConverter))]
        [JsonRequired]
                public required System.DateTimeOffset ShippingDate { get; set; }

        /// <summary>
        /// Shipping type code in CTT Correios de Portugal systems
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping_type_code", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [JsonRequired]
                public required string ShippingTypeCode { get; set; }

        /// <summary>
        /// Shipping type code used in CTT Express systems
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping_type_code_es", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        public string ShippingTypeCodeEs { get; set; }

        /// <summary>
        /// Approximate total weight of the shipment (in gr)
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping_weight_declared_gr", Required = Newtonsoft.Json.Required.Always)]
        [JsonRequired]
                public required double ShippingWeightDeclaredGr { get; set; }

        /// <summary>
        /// Used only in PT. When the customer notifies with this code, the Portuguese system prints documentation for presentation in case of police
        /// </summary>
        [Newtonsoft.Json.JsonProperty("transport_fiscal_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string TransportFiscalCode { get; set; }


    }

    /// <summary>
    /// An additional service
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Additionals
    {
        /// <summary>
        /// Additional service code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("additional_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(13)]
        public string AdditionalCode { get; set; }

        /// <summary>
        /// Additional service flag
        /// </summary>
        [Newtonsoft.Json.JsonProperty("additional_flag", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool? AdditionalFlag { get; set; } = false;

        /// <summary>
        /// Description of the additional service
        /// </summary>
        [Newtonsoft.Json.JsonProperty("additional_text", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string AdditionalText { get; set; }

        /// <summary>
        /// Additional service value
        /// </summary>
        [Newtonsoft.Json.JsonProperty("additional_value", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? AdditionalValue { get; set; }

        /// <summary>
        /// Additional service value unit
        /// </summary>
        [Newtonsoft.Json.JsonProperty("additional_value_unit", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string AdditionalValueUnit { get; set; }

        /// <summary>
        /// Object postal charge
        /// </summary>
        [Newtonsoft.Json.JsonProperty("cpo", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Cpo { get; set; }

        /// <summary>
        /// DDA Instructions
        /// </summary>
        [Newtonsoft.Json.JsonProperty("dda_instructions", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string DdaInstructions { get; set; }

        /// <summary>
        /// Code (ID) of the PUDO internally assigned by CTT Express. This code is a combination of the provider code and the point code. This field can be used on ERE and PER additionals
        /// </summary>
        [Newtonsoft.Json.JsonProperty("organic_point_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string OrganicPointCode { get; set; }

        /// <summary>
        /// Code (ID) of the PUDO location using the PUDO provider schema. This field can be used on ERE and PER additionals
        /// </summary>
        [Newtonsoft.Json.JsonProperty("point_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string PointCode { get; set; }

        /// <summary>
        /// Human readable name of the PUDO location. This field can be used on ERE and PER additionals
        /// </summary>
        [Newtonsoft.Json.JsonProperty("point_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string PointName { get; set; }

        /// <summary>
        /// Provider code associated to the PUDO service. This field can be used on ERE and PER additionals
        /// </summary>
        [Newtonsoft.Json.JsonProperty("provider_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ProviderCode { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Audit
    {
        /// <summary>
        /// Datetime when the shipping was created
        /// </summary>
        [Newtonsoft.Json.JsonProperty("created_datetime", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [JsonRequired]
                public required System.DateTimeOffset CreatedDatetime { get; set; }

        /// <summary>
        /// Code of the process that created the manifest
        /// </summary>
        [Newtonsoft.Json.JsonProperty("created_process_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string CreatedProcessCode { get; set; }

        /// <summary>
        /// Creator's user code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("created_user_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string CreatedUserCode { get; set; }

        /// <summary>
        /// Datetime of the last modification
        /// </summary>
        [Newtonsoft.Json.JsonProperty("modified_datetime", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? ModifiedDatetime { get; set; }

        /// <summary>
        /// Code of the process associated with the last modification
        /// </summary>
        [Newtonsoft.Json.JsonProperty("modified_process_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ModifiedProcessCode { get; set; }

        /// <summary>
        /// Comma separated list of reason codes associated with the last modification done to this shipping
        /// </summary>
        [Newtonsoft.Json.JsonProperty("modified_reason_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ModifiedReasonCode { get; set; }

        /// <summary>
        /// User code associated with the last modification
        /// </summary>
        [Newtonsoft.Json.JsonProperty("modified_user_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ModifiedUserCode { get; set; }



        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Delivery
    {
        /// <summary>
        /// Comments about the delivery
        /// </summary>
        [Newtonsoft.Json.JsonProperty("comments", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(1512)]
        public string Comments { get; set; } = "";

        /// <summary>
        /// Contact name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("contact_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string ContactName { get; set; } = "";

        /// <summary>
        /// Latitude coordinate for the delivery
        /// </summary>
        [Newtonsoft.Json.JsonProperty("delivery_latitude_gps", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? DeliveryLatitudeGps { get; set; }

        /// <summary>
        /// Longitude coordinate for the delivery
        /// </summary>
        [Newtonsoft.Json.JsonProperty("delivery_longitude_gps", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? DeliveryLongitudeGps { get; set; }

        /// <summary>
        /// Referral name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("referral_name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        public string ReferralName { get; set; } = "";


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Devolution
    {
        /// <summary>
        /// Devolution address of the devolution action
        /// </summary>
        [Newtonsoft.Json.JsonProperty("devolution_address", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Devolutionaddress DevolutionAddress { get; set; }

        /// <summary>
        /// TRL/AGDD, hub code for devolution
        /// </summary>
        [Newtonsoft.Json.JsonProperty("devolution_destin_hub_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string DevolutionDestinHubCode { get; set; }

        /// <summary>
        /// TRL/AGOD, hub code for devolution
        /// </summary>
        [Newtonsoft.Json.JsonProperty("devolution_origin_hub_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string DevolutionOriginHubCode { get; set; }

        /// <summary>
        /// Shipping code of the related devolution shipping service
        /// </summary>
        [Newtonsoft.Json.JsonProperty("devolution_shipping_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        public string DevolutionShippingCode { get; set; }


    }

    /// <summary>
    /// Represents a shipping item
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Items
    {
        /// <summary>
        /// Code associated with this item on CTT Correios de Portugal
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_code", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [JsonRequired]
                public required string ItemCode { get; set; }

        /// <summary>
        /// Use this value if the shipping code to be used is generated by the client, a range of items agreed with CTT Express and a specific logic for generation must be taken into account
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_code_es", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"^\s*(?!\d{22}000)\d{25}\s*$")]
        public string ItemCodeEs { get; set; }

        /// <summary>
        /// Item comments
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_comments", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ItemComments { get; set; }

        /// <summary>
        /// Item height in cm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_height_declared_cm", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public double? ItemHeightDeclaredCm { get; set; }

        /// <summary>
        /// Item length in cm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_length_declared_cm", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public double? ItemLengthDeclaredCm { get; set; }

        /// <summary>
        /// Order number
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_order", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public double? ItemOrder { get; set; }

        /// <summary>
        /// Item code from the external provider
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_provider_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        public string ItemProviderCode { get; set; }

        /// <summary>
        /// If the label has a barcode other than the one used in CTT Express and an agreement has been reached, this number must be indicated so that it can be read by the Sorters.
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_synonym_code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public string ItemSynonymCode { get; set; }

        /// <summary>
        /// Item weight in gr
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_volumetric_weight_gr", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public double? ItemVolumetricWeightGr { get; set; }

        /// <summary>
        /// Item weight in gr
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_weight_declared_gr", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public double? ItemWeightDeclaredGr { get; set; }

        /// <summary>
        /// Item width in cm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("item_width_declared_cm", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(0D, double.MaxValue)]
        public double? ItemWidthDeclaredCm { get; set; }


    }

    /// <summary>
    /// Represents a Related Shippings item
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class RelatedServices
    {
        /// <summary>
        /// Relation type
        /// </summary>
        [Newtonsoft.Json.JsonProperty("relation_type", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [JsonRequired]
                public required string RelationType { get; set; }

        /// <summary>
        /// Shipping Code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("shipping_code", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(30)]
        [JsonRequired]
                public required string ShippingCode { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class Devolutionaddress
    {
        /// <summary>
        /// Address information
        /// </summary>
        [Newtonsoft.Json.JsonProperty("address", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(256)]
        [JsonRequired]
                public required string Address { get; set; }

        /// <summary>
        /// Country code ISO Alpha 2
        /// </summary>
        [Newtonsoft.Json.JsonProperty("country_code", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.StringLength(2, MinimumLength = 2)]
        [JsonRequired]
                public required string CountryCode { get; set; }

        /// <summary>
        /// Name of the recipient of the devolution
        /// </summary>
        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [JsonRequired]
                public required string Name { get; set; }

        /// <summary>
        /// Devolution notification emails
        /// </summary>
        [Newtonsoft.Json.JsonProperty("notification_emails", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string> NotificationEmails { get; set; }

        /// <summary>
        /// Devolution phone list
        /// </summary>
        [Newtonsoft.Json.JsonProperty("phones", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<string> Phones { get; set; }

        /// <summary>
        /// Postal code
        /// </summary>
        [Newtonsoft.Json.JsonProperty("postal_code", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [JsonRequired]
                public required string PostalCode { get; set; }

        /// <summary>
        /// Town name
        /// </summary>
        [Newtonsoft.Json.JsonProperty("town_name", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [System.ComponentModel.DataAnnotations.StringLength(128)]
        [JsonRequired]
                public required string TownName { get; set; }


    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "11.3.2.0 (Newtonsoft.Json v13.0.0.0)")]
    internal class DateFormatConverter : Newtonsoft.Json.Converters.IsoDateTimeConverter
    {
        public DateFormatConverter()
        {
            DateTimeFormat = "yyyy-MM-dd";
        }
    }
}