name: pipeline
on:
  pull_request:
    types: [opened, edited, reopened, synchronize, closed]

jobs:
  ci:
    uses: PedroHenriques/ci_cd_test_templates/.github/workflows/ci_docker.yml@main
    with:
      environment: "dev"
      deployable_branch_name: 'main'
      source_dir_name: 'src'
      manifest_dir_name: 'Infrastructure'
      custom_service_file_pattern: '*.csproj'
      build_file_pattern: 'Dockerfile'
      deploy_all_services_label_name: 'deploy all services'
    secrets: inherit
