name: pipeline
on:
  pull_request:
    types: [opened, edited, reopened, synchronize, closed]

jobs:
  ci:
    uses: PedroHenriques/ci_cd_workflow_templates/.github/workflows/ci_dotnet_package.yml@v1
    with:
      environment: "dev"
      deployable_branch_name: 'main'
      source_dir_name: 'src'
      deployment_file-or-dir_path: 'build.txt'
      custom_service_file_pattern: '*.csproj'
      build_file_pattern: 'build.txt'
      major_version_label_name: 'major'
      minor_version_label_name: 'minor'
      patch_version_label_name: 'patch'
    secrets: inherit